var de = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualisierung",
	tabplace : "Beobachtungsstandorte",
	hometitel : "Nationale Bodenbeobachtung (NABO) 1985-2009",
	hometext1 : "Die Nationale Bodenbeobachtung (NABO) überwacht mit ihrem Messnetz aus über 100 Dauerbe- obachtungsstandorten seit 1985 die Entwicklung der Schadstoffgehalte unserer Böden. Die Standorte wurden so ausgewählt, dass unterschiedliche Landnutzungstypen (Ackerbau, Grasland, Wald, Spezialkulturen und andere) vertreten sind. Der vorliegende Datensatz präsentiert die Resultate über fünf Erhebungen (1985–2009) für die Schwermetalle Cadmium, Zink, Kupfer, Quecksilber, Blei, Nickel, Chrom und Cobalt.",
	hometext2 : "Visualisierung Schwermetallbelastung des Bodens",
	hometext3 : "Die vorliegende Visualisierung der Schwermetallbelastung basiert auf dem aktuellen Datensatz, welcher durch das Bundesamt für Umwelt auf lindas-data.ch publiziert wird. Die Daten werden online gelesen (SPARQL) und verarbeitet.",
	hometext4 : "Bei den Messdaten handelt es sich Erhebungsmittelwerte von Schwermetall- konzentrationen in den obersten 20 cm des Bodens von rund 100 Dauer- beobachtungsstandorten der Nationalen Bodenbeobachtung NABO.",
	hometext5 : "Handhabung Visualisierung",
	hometext6 : "1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels Mausklick auf einen Kreis werden weitere Details zum Standort und zur zeitlichen</br>Entwicklung angezeigt.",
	hometext6mobile : "1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels einem Fingertipp auf den Link «Zeitliche Entwicklung» im Tooltip werden weitere Details</br>zum Standort und zur zeitlichen Entwicklung angezeigt.",
	errortext : "Die Daten konnten nicht online gelesen werden. Es werden Erhebungsdaten vom Juli 2016 verwendet.",
	chooseLanduse: "Landnutzung alle",
	chooseParameter: "Schwermetall wählen",
	chooseSurvey: "Beprobungszeitraum: ",
	guidanceLevel: "Richtwert",
	municipality: "Standort",
	municipalityID: "Standort ID",
	altitude: "Höhe",
	landuse: "Landnutzung",
	parameter: "Schwermetall",
	measurement: "Wert",
	unit: "Einheit",
	altitudeUnit: "m ü. M.",
	valueNA: "Kein Messresultat",
	cropCultivation: "Ackerbau",
	vegetableGrowing: "Gemüsebau",
	grasslandIntensiv: "Grasland, intensiv",
	grasslandExtensiv: "Grasland, extensiv",
	grasslandLessIntensive: "Grasland, wenig intensiv",
	deciduousForest: "Laubwald",
	mixedForest: "Mischwald",
	coniferousForest: "Nadelwald",
	fruitGrowing: "Obstbau",
	viticulture: "Rebbau",
	protectedSite: "Schutzstandort",
	urbanPark: "Stadtpark",
	crop: "Ackerbau",
	grassland: "Grasland (intensiv, wenig intensiv, extensiv)",
	forest: "Wald (Laub-, Misch- und Nadelwald)",
	specialGrowing: "Spezialkulturen (Gemüse-, Obst- und Rebbau)",
	other: "Andere (Schutzstandort, Stadtpark)",
	naboPlaces: "NABO-Dauerbeobachtungsstandorte und Nutzung bei der 5. Erhebung",
	titelParameter: "Beschreibung Schwermetalle",
	unitValue: "mg/kg Trockensubstanz (TS)",
	unitValueShort: "mg/kg TS",
	unitValueLegend: "TS = Trockensubstanz",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=de",
	glossarUrlText: "Schadstoffglossar Bundesamt für Umwelt (BAFU)",
	maxValue: "Maximalwert",
	dateSampling: "Probenahmedatum",
	parameterinfo: "Details zum gewählten Schwermetall",
	landuseinfo: "Details zur gewählten Landnutzung",
	placeinfo: "Details zum gewählten Standort",
	howto: "Zeitliche Entwicklung",
	linkVis: "Daten- visualisierung"
};

var fr = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualisation",
	tabplace : "de-Beobachtungsstandorte",
	hometitel : "Observatoire national des sols (NABO) 1985 à 2009",
	hometext1 : "S'appuyant sur un réseau de mesure de 103 sites d’observation à long terme, l’Observatoire national des sols (NABO) surveille depuis 1985 l’évolution des teneurs en polluants de nos sols. Les sites ont été choisis afin d’être représentatifs de différents types d’utilisation (grandes cultures, herbages, forêt et cultures spéciales). Ce rapport présente les résul- tats de cinq cycles de mesures (1985–2009) portant sur les métaux lourds cadmium, zinc, cuivre, mercure, plomb, nickel, chrome et cobalt.",
	hometext2 : "de-Visualisierung Schwermetallbelastung des Bodens",
	hometext3 : "de-Die vorliegende Visualisierung der Schwermetallbelastung basiert auf dem aktuellen Datensatz, welcher durch das Bundesamt für Umwelt auf lindas-data.ch publiziert wird. Die Daten werden online gelesen (SPARQL) und verarbeitet.",
	hometext4 : "de-Bei den Messdaten handelt es sich Erhebungsmittelwerte von Schwermetallkonzentrationen in den obersten 20 cm des Bodens von rund 100 Dauerbeobachtungsstandorten der Nationalen Boden- beobachtung NABO.",
	hometext5 : "de-Handhabung Visualisierung",
	hometext6 : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels Mausklick auf einen Kreis werden weitere Details zum Standort und zur zeitlichen</br>Entwicklung angezeigt.",
	hometext6mobile : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels einem Fingertipp auf den Link «Zeitliche Entwicklung» im Tooltip werden weitere Details</br>zum Standort und zur zeitlichen Entwicklung angezeigt.",
	errortext : "de-Die Daten konnten nicht online gelesen werden. Es werden Erhebungsdaten vom Juli 2016 verwendet.",
	chooseLanduse: "de-Landnutzung alle",
	chooseParameter: "de-Schwermetall wählen",
	chooseSurvey: "de-Beprobungszeitraum: ",
	guidanceLevel: "Valeur indicative",
	municipality: "Site",
	municipalityID: "Site ID",
	altitude: "Altitude",
	landuse: "Utilisation",
	parameter: "Métal lourd ",
	measurement: "Valeur",
	unit: "Unité",
	altitudeUnit: "de-m ü. M.",
	valueNA: "de-Kein Messresultat",
	cropCultivation: "culture des champs",
	vegetableGrowing: "culture maraîchère",
	grasslandIntensiv: "prairie intensive",
	grasslandExtensiv: "prairie extensive",
	grasslandLessIntensive: "prairie peu intensive",
	deciduousForest: "forêt feuillue",
	mixedForest: "forêt mixte",
	coniferousForest: "forêt résineuse",
	fruitGrowing: "arboriculture",
	viticulture: "viticulture",
	protectedSite: "site protégé",
	urbanPark: "parc urbain",
	crop: "Grandes cultures",
	grassland: "Herbages (intensifs, peu intensifs, extensifs)",
	forest: "Forêts (feuillus, mixtes, résineux)",
	specialGrowing: "Cultures spéciales (culture maraîchère, arbori-, viticulture)",
	other: "Autres (sites protégés, parcs)",
	naboPlaces: "de-NABO-Dauerbeobachtungsstandorte und Nutzung bei der 5. Erhebung",
	titelParameter: "de-Beschreibung Schwermetalle",
	unitValue: "de-mg/kg Trockensubstanz (TS)",
	unitValueShort: "mg/kg MS",
	unitValueLegend: "MS = matière sèche",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=de",
	glossarUrlText: "de-Schadstoffglossar Bundesamt für Umwelt (BAFU)",
	maxValue: "Valeur maximale",
	dateSampling: "de-Probenahmedatum",
	parameterinfo: "de-Details zum gewählten Schwermetall",
	landuseinfo: "de-Details zur gewählten Landnutzung",
	placeinfo: "de-Details zum gewählten Standort",
	howto: "de-Zeitliche Entwicklung",
	linkVis: "de-Datenvisualisierung"
};

var it = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualizzazione",
	tabplace : "de-Beobachtungsstandorte",
	hometitel : "de-Nationale Bodenbeobachtung (NABO) 1985-2009",
	hometext1 : "de-Die Nationale Bodenbeobachtung (NABO) überwacht mit ihrem Messnetz aus 103 Dauerbeobach- tungsstandorten seit 1985 die Entwicklung der Schadstoffgehalte unserer Böden. Die Standorte wurden so ausgewählt, dass unterschiedliche Landnutzungstypen (Ackerbau, Grasland, Wald und Spezialkulturen) vertreten sind. Der vorliegende Datensatz präsentiert die Resultate über fünf Erhebungen (1985–2009) für die Schwermetalle Cadmium, Zink, Kupfer, Quecksilber, Blei, Nickel, Chrom und Cobalt.",
	hometext2 : "de-Visualisierung Schwermetallbelastung des Bodens",
	hometext3 : "de-Die vorliegende Visualisierung der Schwermetallbelastung basiert auf dem aktuellen Datensatz, welcher durch das Bundesamt für Umwelt auf lindas-data.ch publiziert wird. Die Daten werden online gelesen (SPARQL) und verarbeitet.",
	hometext4 : "de-Bei den Messdaten handelt es sich Erhebungsmittelwerte von Schwermetallkonzentrationen in den obersten 20 cm des Bodens von rund 100 Dauerbeobachtungsstandorten der Nationalen Boden- beobachtung NABO.",
	hometext5 : "de-Handhabung Visualisierung",
	hometext6 : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels Mausklick auf einen Kreis werden weitere Details zum Standort und zur zeitlichen</br>Entwicklung angezeigt.",
	hometext6mobile : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels einem Fingertipp auf den Link «Zeitliche Entwicklung» im Tooltip werden weitere Details</br>zum Standort und zur zeitlichen Entwicklung angezeigt.",
	errortext : "de-Die Daten konnten nicht online gelesen werden. Es werden Erhebungsdaten vom Juli 2016 verwendet.",
	chooseLanduse: "de-Landnutzung alle",
	chooseParameter: "de-Schwermetall wählen",
	chooseSurvey: "de-Beprobungszeitraum: ",
	guidanceLevel: "Valori indicativo",
	municipality: "Sito",
	municipalityID: "Sito ID",
	altitude: "Altitudine",
	landuse: "Utilizzo del suolo",
	parameter: "Metallo pesante",
	measurement: "Valore",
	unit: "Unità",
	altitudeUnit: "de-m ü. M.",
	valueNA: "de-Kein Messresultat",
	cropCultivation: "campicoltura",
	vegetableGrowing: "orticoltura",
	grasslandIntensiv: "prato, intensivo",
	grasslandExtensiv: "prato, estensivo",
	grasslandLessIntensive: "prato, poco intensivo",
	deciduousForest: "bosco di latifoglie",
	mixedForest: "bosco misto",
	coniferousForest: "bosco di conifere",
	fruitGrowing: "frutticoltura",
	viticulture: "viticoltura",
	protectedSite: "sito protetto",
	urbanPark: "parco urbano",
	crop: "Campicoltura",
	grassland: "Superfici inerbate (intensivo, poco intensivo, estensivo)",
	forest: "Bosco (bosco di latifoglie, misto, bosco di conifere)",
	specialGrowing: "Colture speciali (orticoltura, frutticoltura, viticoltura)",
	other: "Altro (sito protetto, parco urbano)",
	naboPlaces: "de-NABO-Dauerbeobachtungsstandorte und Nutzung bei der 5. Erhebung",
	titelParameter: "de-Beschreibung Schwermetalle",
	unitValue: "de-mg/kg Trockensubstanz (TS)",
	unitValueShort: "mg/kg SS",
	unitValueLegend: "SS = sostanza secca",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=de",
	glossarUrlText: "de-Schadstoffglossar Bundesamt für Umwelt (BAFU)",
	maxValue: "Valore massimo",
	dateSampling: "de-Probenahmedatum",
	parameterinfo: "de-Details zum gewählten Schwermetall",
	landuseinfo: "de-Details zur gewählten Landnutzung",
	placeinfo: "de-Details zum gewählten Standort",
	howto: "de-Zeitliche Entwicklung",
	linkVis: "de-Datenvisualisierung"
};

var en = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualization",
	tabplace : "de-Beobachtungsstandorte",
	hometitel : "de-Nationale Bodenbeobachtung (NABO) 1985-2009",
	hometext1 : "de-Die Nationale Bodenbeobachtung (NABO) überwacht mit ihrem Messnetz aus 103 Dauerbeobach- tungsstandorten seit 1985 die Entwicklung der Schadstoffgehalte unserer Böden. Die Standorte wurden so ausgewählt, dass unterschiedliche Landnutzungstypen (Ackerbau, Grasland, Wald und Spezialkulturen) vertreten sind. Der vorliegende Datensatz präsentiert die Resultate über fünf Erhebungen (1985–2009) für die Schwermetalle Cadmium, Zink, Kupfer, Quecksilber, Blei, Nickel, Chrom und Cobalt.",
	hometext2 : "de-Visualisierung Schwermetallbelastung des Bodens",
	hometext3 : "de-Die vorliegende Visualisierung der Schwermetallbelastung basiert auf dem aktuellen Datensatz, welcher durch das Bundesamt für Umwelt auf lindas-data.ch publiziert wird. Die Daten werden online gelesen (SPARQL) und verarbeitet.",
	hometext4 : "de-Bei den Messdaten handelt es sich Erhebungsmittelwerte von Schwermetallkonzentrationen in den obersten 20 cm des Bodens von rund 100 Dauerbeobachtungsstandorten der Nationalen Boden- beobachtung NABO.",
	hometext5 : "de-Handhabung Visualisierung",
	hometext6 : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels Mausklick auf einen Kreis werden weitere Details zum Standort und zur zeitlichen</br>Entwicklung angezeigt.",
	hometext6mobile : "de-1. Wechseln Sie zum Register Visualisierung.</br>2. Wählen Sie ein Schwermetall aus. </br>3. Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</br>4. Die Auswahl der Landnutzung ist optional.</br>5. Details zum Standort werden im Tooltip zu jedem Kreis angzeigt.</br>6. Mittels einem Fingertipp auf den Link «Zeitliche Entwicklung» im Tooltip werden weitere Details</br>zum Standort und zur zeitlichen Entwicklung angezeigt.",
	errortext : "de-Die Daten konnten nicht online gelesen werden. Es werden Erhebungsdaten vom Juli 2016 verwendet.",
	chooseLanduse: "Landuse all",
	chooseParameter: "Choose heavy metal",
	chooseSurvey: "de-Beprobungszeitraum: ",
	guidanceLevel: "Guide value",
	municipality: "Site",
	municipalityID: "Site ID",
	altitude: "Altitude",
	landuse: "Landuse",
	parameter: "Heavy metal",
	measurement: "Value",
	unit: "Unit",
	altitudeUnit: "de-m ü. M.",
	valueNA: "de-Kein Messresultat",
	cropCultivation: "crop cultivation",
	vegetableGrowing: "vegetable growing",
	grasslandIntensiv: "grassland, intensiv",
	grasslandExtensiv: "grassland, extensiv",
	grasslandLessIntensive: "grassland, less intensive",
	deciduousForest: "deciduous forest",
	mixedForest: "mixed forest",
	coniferousForest: "coniferous forest",
	fruitGrowing: "fruit growing",
	viticulture: "viticulture",
	protectedSite: "protected site",
	urbanPark: "urban park",
	crop: "Crop cultivation",
	grassland: "Grassland (intensive, less intensive, extensive)",
	forest: "Forest (deciduous-, mixed- und coniferous forest)",
	specialGrowing: "Special Crops (vegetable-, fruit growing, viticulture)",
	other: "Other (protected site, urban park)",
	naboPlaces: "de-NABO-Dauerbeobachtungsstandorte und Nutzung bei der 5. Erhebung",
	titelParameter: "de-Beschreibung Schwermetalle",
	unitValue: "mg/kg dry matter (DM)",
	unitValueShort: "mg/kg DM",
	unitValueLegend: "DM = dry matter",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=de",
	glossarUrlText: "de-Schadstoffglossar Bundesamt für Umwelt (BAFU)",
	maxValue: "Maximum value",
	dateSampling: "de-Probenahmedatum",
	parameterinfo: "de-Details zum gewählten Schwermetall",
	landuseinfo: "de-Details zur gewählten Landnutzung",
	placeinfo: "de-Details zum gewählten Standort",
	howto: "de-Zeitliche Entwicklung",
	linkVis: "Data visualization"
}