var de = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualisierung",
	tabplace : "Beobachtungsstandorte",
	hometext0 : "Nationale Bodenbeobachtung (NABO) 1985-2009",
	hometext1 : "Die Nationale Bodenbeobachtung (NABO) überwacht mit ihrem Messnetz aus über 100 Dauerbeobachtungsstandorten seit 1985 die Entwicklung der Schadstoffgehalte unserer Böden. Die Standorte wurden so ausgewählt, dass unterschiedliche Landnutzungstypen (Ackerbau, Grasland, Wald, Spezialkulturen und andere) vertreten sind. Die verfügbaren Daten präsentieren die Resultate über fünf Erhebungen (1985–2009) für die Schwermetalle Cadmium, Zink, Kupfer, Quecksilber, Blei, Nickel, Chrom und Cobalt.",
	hometext2 : "Visualisierung Schwermetallbelastung des Bodens",
	hometext3 : "Die vorliegende Visualisierung der Schwermetallbelastung basiert auf den aktuellen Daten, welche durch das Bundesamt für Umwelt auf lindas-data.ch publiziert werden. Die Daten werden online gelesen (SPARQL) und verarbeitet.",
	hometext4 : "Bei den Messdaten handelt es sich um Erhebungsmittelwerte von Schwermetallkonzentrationen in den obersten 20 cm des Bodens von rund 100 Dauerbeobachtungsstandorten der Nationalen Bodenbeobachtung NABO.",
	hometext5 : "Handhabung Visualisierung",
	hometext6 : "<ol><li>Wechseln Sie zum Register Visualisierung.</li><li>Wählen Sie ein Schwermetall aus.</li><li>Mit dem Schieberegler können Sie einen Beprobungszeitraum bestim- men (Vorgabe: 2005-09).</li><li>Die Auswahl der Landnutzung ist optional.</li><li>Details zum Standort werden im Tooltip zu jedem Datenpunkt ange- zeigt.</li><li>Mittels Mausklick auf einen Datenpunkt werden weitere Details zum Standort und zur zeitlichen Entwicklung dargestellt.</ol>",
	hometext6mobile : "<ol><li>Wechseln Sie zum Register Visualisierung.</li><li>Wählen Sie ein Schwermetall aus.</li><li>Mit dem Schieberegler können Sie einen Beprobungszeitraum bestimmen (Vorgabe: 2005-09).</li><li>Die Auswahl der Landnutzung ist optional.</li><li>Details zum Standort werden im Tooltip zu jedem Datenpunkt angezeigt.</li><li>Mittels einem Fingertipp auf den Link «Zeitliche Entwicklung» im Tooltip werden weitere Details zum Standort und zur zeitlichen Entwicklung angezeigt.</ol>",
	hometext7 : "Erklärungen zur Visualisierung",
	hometext8 : "Falls ein Standort für einen Zeitpunkt beprobt wurde, für das ent- sprechende Schwermetall jedoch kein Messresultat verfügbar ist, wird dies folgendermassen dargestellt: <ol><li>In der Visualisierung mit einem «X».</li><li>In den Details zur zeitlichen Entwicklung wird für ein beprobtes Schwermetall im Balkendiagramm das Jahr angezeigt, aber kein blauer Balken dargestellt.",
	errortext : "</br>Die Daten konnten nicht online gelesen werden. Es werden Erhebungsdaten vom Dezember 2016 verwendet.",
	landusetext0 : "Allgemeine Informationen zur Landnutzung",
	landusetext1 : "<table><tr><td>Ackerbau</td><td>Fruchtfolgeflächen. Die Fläche wird ackerbaulich genutzt und die Kulturen variieren innerhalb der Fruchtfolge.</td></tr><tr><td>Grasland intensiv</td><td>Mehrmals genutzt und gedüngt pro Saison.</td></tr><tr><td>Grassland wenig intensiv</td><td>Ungefähr dreimal genutzt oder gedüngt pro Saison.</td></tr><tr><td>Grasland extensiv</td><td>Alpweiden oder ungedüngte Naturwiesen.</td></tr><tr><td>Schutzstandort</td><td>Standort in Naturschutzgebieten.</td></tr></table>",
	chooseLanduse: "Landnutzung alle",
	chooseCrop: "Ackerbau",
	chooseGrassland: "Grasland alle",
	chooseForest: "Wald alle",
	chooseSpecialGrowing: "Spezialkulturen alle",
	chooseOther: "Andere alle",
	chooseParameter: "Schwermetall wählen",
	chooseSurvey: "Beprobungszeitraum: ",
	guidanceLevel: "Richtwert",
	municipality: "Standort",
	municipalityID: "Standort ID",
	altitude: "Höhe",
	landuse: "Landnutzung",
	parameter: "Schwermetall",
	measurement: "Wert",
	unit: "Einheit",
	altitudeUnit: "m ü. M.",
	valueNA: "Kein Messresultat",
	cropCultivation: "Ackerbau",
	cropCultivation_descr: "Fläche mit Ackerbau, Kultur variiert über die Jahre in Abhängigkeit der Fruchtfolge, die auch ein- bis mehrjährige Kunstwiese einschliessen kann.",
	vegetableGrowing: "Gemüsebau",
	vegetableGrowing_descr: "Anbau von Gemüse, sehr intensiv.",
	grasslandIntensiv: "Grasland, intensiv",
	grasslandIntensiv_descr: "Permanentes Grasland mit intensiver Nutzung, Anzahl Nutzungen (Schnitt oder Beweidung) und Düngungen abhängig von der Höhenstufe, in Tallagen in der Regel ca. 5 Nutzungen.",
	grasslandExtensiv: "Grasland, extensiv",
	grasslandExtensiv_descr: "Alpweiden und ungedüngte Naturwiesen.",
	grasslandLessIntensive: "Grasland, wenig intensiv",
	grasslandLessIntensive_descr: "Permanentes Grasland mit Nutzung mittlerer Intensität, Anzahl Nutzungen (Schnitt oder Beweidung) und Düngungen abhängig von der Höhenstufe, in Tallagen ca. 3 Nutzungen.",
	deciduousForest: "Laubwald",
	deciduousForest_descr: "Wald, dominiert durch Laubbäume.",
	mixedForest: "Mischwald",
	mixedForest_descr: "Wald, Bestand gemischt.",
	coniferousForest: "Nadelwald",
	coniferousForest_descr: "Wald, dominiert durch Nadelbäume.",
	fruitGrowing: "Obstbau",
	fruitGrowing_descr: "Obstanlage, permanent.",
	viticulture: "Rebbau",
	viticulture_descr: "Reben, permanent.",
	protectedSite: "Schutzstandort",
	protectedSite_descr: "Standorte in Naturschutzgebieten (Hochmoore, im Nationalpark, …).",
	urbanPark: "Stadtpark",
	urbanPark_descr: "städtische Parkanlage (Winterthur, Lugano).",
	crop: "Ackerbau",
	grassland: "Grasland (intensiv, wenig intensiv, extensiv)",
	forest: "Wald (Laub-, Misch- und Nadelwald)",
	specialGrowing: "Spezialkulturen (Gemüse-, Obst- und Rebbau)",
	other: "Andere (Schutzstandort, Stadtpark)",
	naboPlaces: "NABO-Dauerbeobachtungsstandorte und Nutzung bei der 5. Erhebung",
	titelParameter: "Beschreibung Schwermetalle",
	Cd_descr: "Cadmium ist für den Menschen besonders schädlich und verursacht u.a. Schäden an Nieren, Knochen und dem zentralen Nervensystem. Es gelangt über atmosphärische Deposition und als Verunreinigung in mineralischen Phosphordüngern in den Boden, je nach Geologie können die Gehalte auch natürlicherweise erhöht sein. Pflanzen (insbesondere einige Gemüse und Weizen) nehmen Cadmium aus dem Boden auf, wodurch dieses in die menschliche Nahrungskette gelangt.",
	Pb_descr: "Für Blei ist die atmosphärische Deposition der wichtigste Eintragspfad in den Boden. Aufgrund der getroffenen Massnahmen, insbesondere der Verbannung des Blei aus Krafttreibstoffen, hat die Bleibelastung der Luft seit den 1980er-Jahren deutlich abgenommen, wodurch auch die Einträge in die Böden rückläufig sind. Eine erhöhte Aufnahme ist für den Menschen schädlich.",
	Cu_descr: "Kupfer gelangt(e) zum einen als Bestandteil von Pflanzenschutzmitteln, insbesondere Fungiziden, in die Böden, wodurch viele Rebberge und Gemüsebauflächen erhöhte Konzentrationen aufweisen. Zum anderen gelangt Kupfer mit Gülle und Mist auf die Felder, da es der Tiernahrung zugesetzt wird. Schliesslich können die Gehalte aufgrund der Geologie auch natürlicherweise erhöht sein. Kupfer ist in geringen Mengen essentiell für Tier und Mensch, bei hoher Aufnahme jedoch toxisch.",
	Zn_descr: "Zink gelangt über atmosphärische Deposition sowie mit Gülle und Mist auf die Felder, seine Gehalte können aber auch natürlicherweise aufgrund der Geologie erhöht sein. Zink ist ein essentielles Spurenelement für Tier und Mensch. Erhöhte Gehalte im Boden können jedoch Pflanzen und Bodenlebewesen beeinträchtigen.",
	Hg_descr: "Quecksilber ist ein stark toxisches Schwermetall, das sich in der Nahrungskette anreichert. Bei chronischen Belastungen werden vor allem die Nieren und das zentrale Nervensystem geschädigt. Eine Gefahr besteht insbesondere durch die Aufnahme von Bodenstäuben (oder Bodenmaterial bei Kindern) sowie das Einatmen von Quecksilberdämpfen (Quecksilber weist einen hohen Dampfdruck auf). Als besonders giftig wird Methylquecksilber betrachtet, dieses wird durch Mikroorganismen aus dem Quecksilber im Boden gebildet. Quecksilber gelangt durch eine Vielzahl von Prozessen, insbesondere Industrie und Verbrennung, in die Umwelt, ist aber auch in einigen Pflanzenschutzmitteln enthalten.",
	Ni_descr: "Die Gehalte der drei Elemente Nickel, Chrom, Kobalt werden in erster Linie durch die Geologie bestimmt (geogene Gehalte). Einträge durch menschliche Aktivitäten sind an Standorten mit direkten Immissionen (z. B. Altlastenstandorte) relevant, im NABO-Messnetz sind keine solchen Standorte enthalten.",
	Cr_descr: "Die Gehalte der drei Elemente Nickel, Chrom, Kobalt werden in erster Linie durch die Geologie bestimmt (geogene Gehalte). Einträge durch menschliche Aktivitäten sind an Standorten mit direkten Immissionen (z. B. Altlastenstandorte) relevant, im NABO-Messnetz sind keine solchen Standorte enthalten.",
	Co_descr: "Die Gehalte der drei Elemente Nickel, Chrom, Kobalt werden in erster Linie durch die Geologie bestimmt (geogene Gehalte). Einträge durch menschliche Aktivitäten sind an Standorten mit direkten Immissionen (z. B. Altlastenstandorte) relevant, im NABO-Messnetz sind keine solchen Standorte enthalten.",
	noHeavyMetal: "Kein Schwermetall gewählt.",
	noLanduse: "Keine Landnutzung gewählt.",	
	unitValue: "mg/kg Trockensubstanz (TS)",
	unitValueShort: "mg/kg TS",
	unitValueLegend: "TS = Trockensubstanz",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=de",
	glossarUrlText: "Schadstoffglossar Bundesamt für Umwelt (BAFU)",
	maxValue: "Maximalwert",
	dateSampling: "Probenahmedatum",
	parameterinfo: "Details zum gewählten Schwermetall",
	landuseinfo: "Details zur Landnutzung",
	placeinfo: "Details zum gewählten Standort",
	howto: "Zeitliche Entwicklung",
	linkVis: "Daten- visualisierung",
	linkNabo: "Webseite NABO",
	nabo8504: "https://www.bafu.admin.ch/bafu/de/home/themen/boden/publikationen-studien/publikationen/nationale-bodenbeobachtung-nabo-1985-2004.html",
	nabo8509: "https://www.bafu.admin.ch/bafu/de/home/themen/boden/publikationen-studien/publikationen/bodenbeobachtung-nabo-1985-2009.html",
	pubtext8504: "Ergebnisse der Nationalen Bodenbeobachtung (NABO) 1985−2004",
	pubtext8509: "Ergebnisse der Nationalen Bodenbeobachtung (NABO) 1985−2009",
	noMeasurement: "Beprobt, kein Messresultat",
	ubd0066: "http://www.ubst.bafu.admin.ch/opendata/UBD0066.ods",
	textubd0066: "Spezifikation und Daten der Schwermetallbelastung des Bodens"
};

var fr = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Accueil",
	tabvis : "Visualisation",
	tabplace : "Sites d'observation",
	hometext0 : "Observatoire national des sols (NABO) 1985 à 2009",
	hometext1 : "S'appuyant sur un réseau de 103 sites d’observation à long terme, l’Observatoire national des sols (NABO) surveille l’évolution des teneurs en polluants des sols depuis 1985. Les sites choisis sont représentatifs de différents types d’utilisation (grandes cultures, herbages, forêts et cultures spéciales). Ce rapport présente les résultats de cinq cycles de mesures (1985–2009) portant sur les métaux lourds que sont le cadmium, le zinc, le cuivre, le mercure, le plomb, le nickel, le chrome et le cobalt.",
	hometext2 : "Visualisation de la pollution des sols par les métaux lourds",
	hometext3 : "Cette visualisation de la pollution des sols par les métaux lourds se base sur des données actuelles publiées par l'Office fédéral de l'environnement (OFEV) sur lindas-data.ch. Ces données peuvent être consultées en ligne (SPARQL) et traitées.",
	hometext4 : "Les données mesurées sont des moyennes des concentrations de métaux lourds relevées sur les 20 cm supérieurs du sol sur 100 sites d'observation à long terme de l'Observatoire national des sols (NABO).",
	hometext5 : "Paramétrage",
	hometext6 : "<ol><li>Cliquez sur l'onglet Visualisation.</li><li>Sélectionnez un métal lourd.</li><li>À l'aide du curseur, vous pouvez définir une période d'échantillonnage (par défaut 2005-2009).</li><li>Il n'est pas obligatoire de sélectionner une utilisation du sol.</li><li>Les détails de chaque site s'affichent dans une infobulle.</li><li>Lorsque vous cliquez sur un site, d'autres informations sur le site s'affichent ainsi que l'évolution temporelle de ses mesures.</ol>",
	hometext6mobile : "<ol><li>Cliquez sur l'onglet Visualisation.</li><li>Sélectionnez un métal lourd.</li><li>À l'aide du curseur, vous pouvez définir une période d'échantillonnage (par défaut 2005-2009).</li><li>Il n'est pas obligatoire de sélectionner une utilisation du sol.</li><li>Les détails de chaque site s'affichent dans une infobulle.</li><li>Par une pression du doigt sur le lien «évolution temporelle» dans l'infobulle, d'autres informations sur le site s'affichent ainsi que l'évolution temporelle de ses mesures.</ol>",
	hometext7 : "Explications",
	hometext8 : "L'absence de résultats pour le métal lourd sélectionné, même si le site a fait l'objet d'échantillonnages, est signalée comme suit : <ol><li>Un « x » s'affiche sur la visualisation.</li><li>Dans les informations sur l'évolution temporelle des mesures, l'année est indiquée, mais aucune barre bleu ne s'affiche pour le métal lourd concerné.",
	errortext : "</br>Les données n'ont pas pu être consultées en ligne. Les données des relevés de décembre 2016 sont utilisées.",
	landusetext0 : "Utilisation du sol : généralités",
	landusetext1 : "<table><tr><td>grandes cultures</td><td>surfaces d’assolement. Les surfaces sont cultivées et les cultures se succèdent en fonction de l'assolement.</td></tr><tr><td>herbages intensifs</td><td>exploités et fertilisés plusieurs fois par saison.</td></tr><tr><td>herbages peu intensifs</td><td>exploités et fertilisés env. 3 fois par saison.</td></tr><tr><td>herbages extensifs</td><td>alpages ou prairies naturelles non fertilisés.</td></tr><tr><td>site protégé</td><td>site dans aire protégée.</td></tr></table>",
	chooseLanduse: "utilisations, toutes",
	chooseCrop: "grandes cultures",
	chooseGrassland: "herbages, tous",
	chooseForest: "forêts, toutes",
	chooseSpecialGrowing: "cultures spéciales, toutes",
	chooseOther: "autres",
	chooseParameter: "Sélectionner un métal lourd",
	chooseSurvey: "Période d'échantillonnage: ",
	guidanceLevel: "valeur indicative",
	municipality: "site",
	municipalityID: "sigle",
	altitude: "altitude",
	landuse: "utilisation du sol",
	parameter: "métal lourd ",
	measurement: "valeur",
	unit: "unité",
	altitudeUnit: "m d'altitude",
	valueNA: "aucune mesure",
	cropCultivation: "culture des champs",
	cropCultivation_descr: "surfaces cultivées et assolées, qui peuvent également consister en des prairies artificielles pendant une voire plusieurs années.",
	vegetableGrowing: "culture maraîchère",
	vegetableGrowing_descr: "culture maraîchère, exploitée de manière très intensive.",
	grasslandIntensiv: "prairie intensive",
	grasslandIntensiv_descr: "prairie permanente exploitée de manière intensive, dont le nombre d'utilisations (coupe ou pacage) et d'épandages est fonction de l'altitude (env. 5 utilisations dans les vallées).",
	grasslandExtensiv: "prairie extensive",
	grasslandExtensiv_descr: "prairie alpestre ou prairie naturelle non fertilisée.",
	grasslandLessIntensive: "prairie peu intensive",
	grasslandLessIntensive_descr: "prairie permanente exploitée de manière moyennement intensive, dont le nombre d'utilisations (coupe ou pacage) et d'épandages est fonction de l'altitude (env. 3 utilisations dans les vallées).",
	deciduousForest: "forêt feuillue",
	deciduousForest_descr: "forêt où les feuillus prédominent.",
	mixedForest: "forêt mixte",
	mixedForest_descr: "forêt à peuplement mixte.",
	coniferousForest: "forêt résineuse",
	coniferousForest_descr: "forêt où les résineux prédominent.",
	fruitGrowing: "arboriculture",
	fruitGrowing_descr: "installation permanente d'arboriculture.",
	viticulture: "viticulture",
	viticulture_descr: "vignoble permanent.",
	protectedSite: "site protégé",
	protectedSite_descr: "site dans une aire protégée (haut-marais, Parc national, etc.).",
	urbanPark: "parc urbain",
	urbanPark_descr: "parc urbain (Winterthour, Lugano).",
	crop: "culture des champs",
	grassland: "herbages (intensifs, peu intensifs, extensifs)",
	forest: "forêts (feuillus, mixtes, résineux)",
	specialGrowing: "cultures spéciales (culture maraîchère, arbori-, viticulture)",
	other: "autres (sites protégés, parcs urbains)",
	naboPlaces: "sites d'observation à long terme NABO et utilisation lors du 5e relevé",
	titelParameter: "Métaux lourds : description",
	Cd_descr: "métal lourd particulièrement nocif pour la santé humaine qui cause, notamment, des dommages aux reins, aux os et au système nerveux central. Le cadmium est présent dans les sols en raison de dépôts atmosphériques et de l'épandage d'engrais minéraux phosphorés. Toutefois, selon la géologie, certains sols peuvent présenter des teneurs en cadmium naturellement élevées. Le cadmium se retrouve dans la chaîne alimentaire, car les végétaux (en particulier certains légumes et blés) l'absorbent dans le sol.",
	Pb_descr: "métal lourd dont l'apport dans les sols est principalement dû à des dépôts atmosphériques. Grâce aux mesures prises, en particulier l'interdiction du plomb dans les carburants, la pollution de l'air due à ce métal lourd a nettement diminué depuis les années 1980, et, en conséquence, celle des sols. L'absorption de teneurs élevées est nocive pour la santé humaine.",
	Cu_descr: "métal lourd dont l'apport dans les sols est (était) dû à deux causes : utilisation de produits phytosanitaires, en particulier de fongicides, raison pour laquelle nombre de vignobles et cultures maraîchères présentent des concentrations élevées de cuivre, et épandage de lisier et de fumier, du cuivre étant ajouté aux aliments des animaux. Selon la géologie, certains sols peuvent présenter des teneurs en cuivre naturellement élevées. Ce métal lourd est un oligoélément essentiel aux hommes et aux animaux, mais toxique à haute dose.",
	Zn_descr: "métal lourd dont l'apport dans les sols est dû aux dépôts atmosphériques et à l'épandage de lisier et de fumier. Toutefois, selon la géologie, certains sols peuvent présenter des teneurs en zinc naturellement élevées. Le zinc est un oligoélément essentiel aux hommes et aux animaux. Cependant, des teneurs élevées dans les sols peuvent porter atteinte aux plantes et aux organismes du sol.",
	Hg_descr: "métal lourd hautement toxique, qui s'accumule le long de la chaîne alimentaire. Des expositions chroniques au mercure causent des dommages principalement aux reins et au système nerveux central. Le véritable danger résulte de l'absorption de particules de terre (ou de terre par les enfants) et de la respiration de vapeurs de mercure, celui-ci présentant une pression de vapeur élevée. Le méthylmercure est particulièrement toxique et se forme à partir de mercure sous l'action de microorganismes dans le sol. De nombreux processus, notamment industriels et de combustion, sont responsables de l'apport de ce métal lourd dans l'environnement. En outre, certains produits phytosanitaires en contiennent.",
	Ni_descr: "métaux lourds dont les teneurs dans les sols sont avant tout dues à la géologie (teneurs géogènes). Les sites exposés à des immissions directes (p. ex. sites contaminés) enregistrent néanmoins des apports d'origine anthropique. Le réseau des stations de mesure NABO ne contient aucun site de ce genre.",
	Cr_descr: "métaux lourds dont les teneurs dans les sols sont avant tout dues à la géologie (teneurs géogènes). Les sites exposés à des immissions directes (p. ex. sites contaminés) enregistrent néanmoins des apports d'origine anthropique. Le réseau des stations de mesure NABO ne contient aucun site de ce genre.",
	Co_descr: "métaux lourds dont les teneurs dans les sols sont avant tout dues à la géologie (teneurs géogènes). Les sites exposés à des immissions directes (p. ex. sites contaminés) enregistrent néanmoins des apports d'origine anthropique. Le réseau des stations de mesure NABO ne contient aucun site de ce genre.",
	noHeavyMetal: "Aucun métal lourd choisi.",
	noLanduse: "Aucune utilisation du sol sélectionné.",
	unitValue: "matière sèche (MS) mg/kg",
	unitValueShort: "MS mg/kg",
	unitValueLegend: "MS = matière sèche",	
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=fr",
	glossarUrlText: "Glossaire des polluants atmosphériques",
	maxValue: "valeur maximale",
	dateSampling: "date de l'échantillonnage",
	parameterinfo: "Informations",
	landuseinfo: "Informations",
	placeinfo: "Informations",
	howto: "évolution temporelle",
	linkVis: "Visualisation des données",
	linkNabo: "site Internet NABO",
	nabo8504: "https://www.bafu.admin.ch/bafu/fr/home/themes/sol/publications-etudes/publications/observatoire-national-sols-nabo-1985-2004.html",
	nabo8509: "https://www.bafu.admin.ch/bafu/fr/home/themes/sol/publications-etudes/publications/observatoire-national-sols-nabo-1985-2009.html",
	pubtext8504: "Résultats de l'Observatoire national des sols (NABO) 1985-2004",
	pubtext8509: "Résultats de l'Observatoire national des sols (NABO) 1985-2009",
	noMeasurement: "échantillonné, mais aucune mesure",
	ubd0066: "http://www.ubst.bafu.admin.ch/opendata/UBD0066.ods",
	textubd0066: "Spécifications et données de la pollution par les métaux lourds du sol"
};

var it = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualizzazione",
	tabplace : "Siti di osservazione",
	hometext0 : "Osservatorio nazionale dei suoli (NABO) dal 1985 al 2009",
	hometext1 : "Con la sua rete composta di 103 siti di osservazione a lungo termine, l'Osservatorio nazionale dei suoli (NABO) sorveglia dal 1985 l'evoluzione dei carichi di sostanze inquinante nei suoli. I siti scelti sono rappresentativi per diverse tipologie di utilizzazione (campicolture, prati, boschi, colture speciali e altri). Il presente record di dati illustra i risultati di cinque rilevamenti (1985-2009) che hanno interessato i metalli pesanti cadmio, zinco, rame, mercurio, piombo, nichel, cromo e cobalto.",
	hometext2 : "Visualizzazione del carico di metalli pesanti nel suolo",
	hometext3 : "La presente visualizzazione dell'inquinamento dei suoli da metalli pesanti si basa sui dati aggiornati pubblicati dall'Ufficio federale dell'ambiente (UFAM) su http://lindas-data.ch. Questi dati possono essere consultati online (SPARQL) ed elaborati.",
	hometext4 : "I dati misurati sono valori medi delle concentrazioni di metalli pesanti rilevate nei 20 cm dello strato superiore del suolo presso circa 100 siti di osservazione a lungo termine dell'Osservatorio nazionale dei suoli (NABO).",
	hometext5 : "Parametraggio",
	hometext6 : "<ol><li>Cliccare sulla linguetta Visualizzazione.</li><li>Selezionare un metallo pesante.</li><li>Con l'aiuto del cursore potete definire il periodo di rilevamento (periodo predefinito: 2005-2009).</li><li>La selezione dell'utilizzo del suolo non è obbligatoria.</li><li>Le informazioni dettagliate relative al sito appaiono in un tooltip.</li><li>Cliccando su un punto di dati, appaiono informazioni supplementari sul sito e sull'evoluzione temporale.</ol>",
	hometext6mobile : "<ol><li>Cliccare sulla linguetta Visualizzazione.</li><li>Selezionare un metallo pesante.</li><li>Con l'aiuto del cursore potete definire il periodo di rilevamento (periodo predefinito: 2005-2009).</li><li>La selezione dell'utilizzo del suolo non è obbligatoria.</li><li>Le informazioni dettagliate relative al sito appaiono in un tooltip.</li><li>Cliccando sul link «Evoluzione temporale» che trovate nel tooltip, accedete a informazioni supplementari sul sito e sull'evoluzione temporale.</ol>",
	hometext7 : "Spiegazioni",
	hometext8 : "Se il sito è stato oggetto di campionamento ma non si dispongono dati per il metallo pesante selezionato: <ol><li>Nella visualizzazione appare una «x».</li><li>Per un metallo pesante oggetto di campionamento, nelle informazioni dettagliate sull'evoluzione temporale viene indicato l'anno ma non è rappresentata alcuna barra blu.",
	errortext : "</br>I dati non hanno potuto essere consultati online. Vengono utilizzati quelli rilevati nel dicembre 2016.",
	landusetext0 : "Utilizzo del suolo: informazioni generali",
	landusetext1 : "<table><tr><td>campicoltura</td><td>avvicendamento delle colture. Le superfici sono coltivate e le colture variano in funzione della rotazione delle colture.</td></tr><tr><td>prati intensivi</td><td>utilizzati e concimati più volte/stagione.</td></tr><tr><td>prati poco intensivi</td><td>utilizzati e concimati circa 3 volte/stagione.</td></tr><tr><td>prati estensivi</td><td>alpeggi o praterie naturali non concimati.</td></tr><tr><td>siti protetti</td><td>siti all'interno di zone protette.</td></tr></table>",
	chooseLanduse: "Utilizzazione, tutti i tipi",
	chooseCrop: "campicoltura",
	chooseGrassland: "prato, tutti i tipi",
	chooseForest: "bosco, tutti i tipi",
	chooseSpecialGrowing: "colture speciali, tutti i tipi",
	chooseOther: "altri",
	chooseParameter: "Selezionare un metallo pesante",
	chooseSurvey: "Periodo di campionamento: ",
	guidanceLevel: "Valore indicativo",
	municipality: "Sito",
	municipalityID: "ID del sito",
	altitude: "Altitudine",
	landuse: "Utilizzo del suolo",
	parameter: "Metallo pesante",
	measurement: "Valore",
	unit: "Unità",
	altitudeUnit: "m s.l.m.",
	valueNA: "nessuna misura",
	cropCultivation: "campicoltura",
	cropCultivation_descr: "Superficie utilizzata per la campicoltura: le colture variano in funzione della rotazione delle colture; può includere anche i prati artificiali annuali o pluriennali.",
	vegetableGrowing: "orticoltura",
	vegetableGrowing_descr: "Coltivazione di ortaggi a uso molto intensivo.",
	grasslandIntensiv: "prato, intensivo",
	grasslandIntensiv_descr: "Superficie inerbata permanente a uso intensivo, il numero di utilizzi (sfalcio o pascolo) e di concimazioni dipende dall'altitudine, nelle zone di valle si contano di regola circa cinque utilizzi.",
	grasslandExtensiv: "prato, estensivo",
	grasslandExtensiv_descr: "Pascolo alpestre e prato naturale non concimato.",
	grasslandLessIntensive: "prato, poco intensivo",
	grasslandLessIntensive_descr: "Superficie inerbata permanente a uso intensivo medio, il numero di utilizzi (sfalcio o pascolo) e di concimazioni dipende dall'altitudine, nelle zone di valle si contano di regola circa tre utilizzi.",
	deciduousForest: "bosco di latifoglie",
	deciduousForest_descr: "Bosco prevalentemente di latifoglie.",
	mixedForest: "bosco misto",
	mixedForest_descr: "Bosco di composizione mista.",
	coniferousForest: "bosco di conifere",
	coniferousForest_descr: "Bosco prevalentemente di conifere.",
	fruitGrowing: "frutticoltura",
	fruitGrowing_descr: "Frutteto permanente.",
	viticulture: "viticoltura",
	viticulture_descr: "Vigneto permanente.",
	protectedSite: "sito protetto",
	protectedSite_descr: "Siti in zone protette (paludi, Parco nazionale ecc.).",
	urbanPark: "parco urbano",
	urbanPark_descr: "Parco situato in città (Winterthur, Lugano).",
	crop: "campicoltura",
	grassland: "superfici inerbate (intensivo, poco intensivo, estensivo)",
	forest: "bosco (bosco di latifoglie, misto, di conifere)",
	specialGrowing: "colture speciali (orticoltura, frutticoltura, viticoltura)",
	other: "altro (sito protetto, parco urbano)",
	naboPlaces: "Siti di osservazione a lungo termine NABO e utilizzazione nell'ambito del 5. rilevamento",
	titelParameter: "Metalli pesanti: descrizione",
	Cd_descr: "Il cadmio è particolarmente dannoso per l'uomo e causa problemi a reni, ossa e sistema nervoso centrale. Raggiunge il suolo attraverso la deposizione atmosferica e come contaminante nei fertilizzanti minerali a base di fosforo. I tenori elevati possono anche avere cause naturali a seconda delle condizioni geologiche. Le piante (in particolare alcuni ortaggi e cereali) assorbono cadmio dal terreno, che entra in tal modo nella catena alimentare dell'uomo.",
	Pb_descr: "Il piombo raggiunge il suolo principalmente attraverso la deposizione atmosferica. A partire dagli anni Ottanta, le misure adottate, in particolare l'eliminazione del pimbo nei carburanti, hanno consentito di ridurre sensibilmente l'inquinamento atmosferico da piombo e quindi anche le sue concentrazioni nei suoli. Un'assunzione elevata è dannosa per l'uomo.",
	Cu_descr: "Il rame raggiunge(va) il suolo, da un lato, come componente dei prodotti fitosanitari, in particolare fungicidi. Per questo motivo, numerosi vigneti e superfici utilizzate per la coltivazione di ortaggi presentano concentrazioni elevate. Dall'altro, è contenuto nel letame e nel colaticcio sparsi sui campi in quanto il rame è addizionato al foraggio per animali. Infine, i tenori elevati possono anche avere cause naturali a seconda delle condizioni geologiche. In quantità ridotte il rame è essenziale per l'uomo e gli animali, ma risulta tossico in caso di assunzione elevata.",
	Zn_descr: "Lo zinco raggiunge il suolo attraverso la deposizione atmosferica e il letame e il colaticcio sparsi sui campi. Il tenore elevato può anche avere cause naturali a seconda delle condizioni geologiche. Lo zinco è un elemento in tracce essenziale per l'uomo e gli animali. Concentrazioni elevate nel suolo possono tuttavia danneggiare piante e organismi del suolo.",
	Hg_descr: "Il mercurio è un metallo pesante molto tossico che si accumula nella catena alimentare. In caso di inquinamento cronico danneggia soprattutto i reni e il sistema nervoso centrale. Sussiste un pericolo in particolare in caso di assunzione di polveri sollevate dal terreno (o di materiale terroso nel caso dei bambini) e di inalazione di vapori di mercurio (il mercurio è caratterizzato da un'elevata pressione di vapore). Il metilmercurio, che si forma dal mercurio nel suolo per azione di microrganismi, è considerato particolarmente tossico. Il mercurio viene immesso nell'ambiente attraverso numerosi processi legati soprattutto all'industria e alla combustione, ma è contenuto anche in alcuni prodotti fitosanitari.",
	Ni_descr: "I tenori dei tre elementi nichel, cromo e cobalto sono determinati in primo luogo dalla geologia (tenori geogeni). Gli apporti delle attività antropiche sono importanti nei siti caratterizzati da immissioni dirette (p. es. siti contaminati). La rete di misurazione NABO non include alcun sito di questo genere.",
	Cr_descr: "I tenori dei tre elementi nichel, cromo e cobalto sono determinati in primo luogo dalla geologia (tenori geogeni). Gli apporti delle attività antropiche sono importanti nei siti caratterizzati da immissioni dirette (p. es. siti contaminati). La rete di misurazione NABO non include alcun sito di questo genere.",
	Co_descr: "I tenori dei tre elementi nichel, cromo e cobalto sono determinati in primo luogo dalla geologia (tenori geogeni). Gli apporti delle attività antropiche sono importanti nei siti caratterizzati da immissioni dirette (p. es. siti contaminati). La rete di misurazione NABO non include alcun sito di questo genere.",
	noHeavyMetal: "Nessun metallo pesante selezionato.",
	noLanduse: "Nessun utilizzo del suolo selezionato.",
	unitValue: "mg/kg sostanza secca (SS)",
	unitValueShort: "SS mg/kg",
	unitValueLegend: "SS = sostanza secca",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=it",
	glossarUrlText: "Glossario degli inquinanti atmosferici",
	maxValue: "Valore massimo",
	dateSampling: "Data del campionamento",
	parameterinfo: "Informazioni dettagliate sui metalli pesanti selezionati",
	landuseinfo: "Informazioni dettagliate sull'utilizzo del suolo",
	placeinfo: "Informazioni dettagliate sul sito selezionato",
	howto: "Evoluzione temporale",
	linkVis: "visualizzazione dei dati",
	linkNabo: "Sito web di NABO",
	nabo8504: "https://www.bafu.admin.ch/bafu/it/home/temi/suolo/pubblicazioni-studi/pubblicazioni/nationale-bodenbeobachtung-nabo-1985-2004.html",
	nabo8509: "https://www.bafu.admin.ch/bafu/it/home/temi/suolo/pubblicazioni-studi/pubblicazioni/bodenbeobachtung-nabo-1985-2009.html",
	pubtext8504: "Risultati dell'Osservatorio nazionale dei suoli (NABO) 1985-2004",
	pubtext8509: "Risultati dell'Osservatorio nazionale dei suoli (NABO) 1985-2009",
	noMeasurement1: "Oggetto di campionamento, nessuna misura",
	noMeasurement: "Campionato, nessun risultato",
	ubd0066: "http://www.ubst.bafu.admin.ch/opendata/UBD0066.ods",
	textubd0066: "Specifiche e dati di inquinamento da metalli pesanti nei terreni"
};

var en = {
	loreipsum : "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
	tabhome : "Home",
	tabvis : "Visualisation",
	tabplace : "Monitoring sites",
	hometext0 : "Swiss National Soil Monitoring Network (NABO) 1985-2009",
	hometext1 : "With its network of over 100 permanent monitoring sites, the National Soil Monitoring Network (NABO) has been monitoring the development of the contaminant content of our soil since 1985. The monitoring sites were selected in such a way that different types of land use (crop cultivation, grassland, forest, special crops and others) are represented. This report presents the findings of five surveys (1985–2009) for the heavy metals cadmium, zinc, copper, mercury, lead, nickel, chrome and cobalt.",
	hometext2 : "Visualisation of heavy metal pollution of the soil",
	hometext3 : "This visualisation of the heavy metal pollution is based on the current data published by the Federal Office for the Environment on lindas-data.ch. The data are read and processed online (SPARQL).",
	hometext4 : "The measurement data are the surveyed mean values of heavy metal concentrations recorded in the top 20 cm of the soil in around 100 permanent monitoring sites operated by the Swiss National Soil Monitoring Network (NABO).",
	hometext5 : "Using the visualisation tool",
	hometext6 : "<ol><li>Change to the Visualisation tab.</li><li>Select a heavy metal.</li><li>You can define a sampling period using the slider (default: 2005-09).</li><li>Selection of the land use type is optional.</li><li>Details about the site are displayed in the Tooltip for each data point.</li><li>Further details about the site and its temporal development can be displayed by clicking the mouse.</ol>",
	hometext6mobile : "<ol><li>Change to the Visualisation tab.</li><li>Select a heavy metal.</li><li>You can define a sampling period using the slider (default: 2005-09).</li><li>Selection of the land use type is optional.</li><li>Details about the site are displayed in the Tooltip for each data point.</li><li>Further details about the site and its temporal development can be displayed by touching the link «Temporal development» in the Tooltip.</ol>",
	hometext7 : "Explanation of the visualisation",
	hometext8 : "If a site was sampled for a period of time but no measured values are available for the corresponding heavy metal, this is indicated as follows: <ol><li>An «X» in the visualisation.</li><li>In the details on the temporal development, the year is shown for a sampled heavy metal in the bar chart but there is no blue bar.",
	errortext : "</br>The data cannot be read online. Survey data from December 2016 are used.",
	landusetext0 : "General information about land use",
	landusetext1 : "<table><tr><td>Crop cultivation</td><td>Crop rotation areas. The site is used for crop cultivation; the crops vary according to the crop rotation system.</td></tr><tr><td>Intensive grassland.</td><td>Harvested and fertilised several times per season.</td></tr><tr><td>Less intensive grassland.</td><td>Harvested or fertilised approximately three times per season.</td></tr><tr><td>Extensive grassland.</td><td>Alpine meadows or unfertilised natural pastures.</td></tr><tr><td>Protected site</td><td>Site located in nature protection area.</td></tr></table>",
	chooseLanduse: "All land uses",
	chooseCrop: "Crop cultivation",
	chooseGrassland: "All grassland",
	chooseForest: "All forest",
	chooseSpecialGrowing: "All special crops",
	chooseOther: "All others",
	chooseParameter: "Choose heavy metal",
	chooseSurvey: "Sampling period: ",
	guidanceLevel: "Guide value",
	municipality: "Site",
	municipalityID: "Site ID",
	altitude: "Altitude",
	landuse: "Land use",
	parameter: "Heavy metal",
	measurement: "Value",
	unit: "Unit",
	altitudeUnit: "m asl",
	valueNA: "No measurement data",
	cropCultivation: "crop cultivation",
	cropCultivation_descr: "Crop cultivation area, crops vary over the years depending on crop rotation, which can also include one or more years of clover-grass mixture.",
	vegetableGrowing: "vegetable growing",
	vegetableGrowing_descr: "Cultivation of vegetables with very intensive use.",
	grasslandIntensiv: "grassland, intensiv",
	grasslandIntensiv_descr: "Permanent grassland with intensive use, number of uses (cutting or grazing) and fertlisation dependent on altitude, approx. 5 uses in valley locations.",
	grasslandExtensiv: "grassland, extensiv",
	grasslandExtensiv_descr: "Alpine meadows and unfertilised natural pastures.",
	grasslandLessIntensive: "grassland, less intensive",
	grasslandLessIntensive_descr: "Permanent grassland with medium-intensity use, number of uses (cutting and grazing) and fertilisation dependent on altitude, approx. 3 uses in valley locations.",
	deciduousForest: "deciduous forest",
	deciduousForest_descr: "Forest, dominated by deciduous trees.",
	mixedForest: "mixed forest",
	mixedForest_descr: "Forest, mixed stand.",
	coniferousForest: "coniferous forest",
	coniferousForest_descr: "Forest, dominated by coniferous trees.",
	fruitGrowing: "fruit growing",
	fruitGrowing_descr: "Orchard, permanent.",
	viticulture: "viticulture",
	viticulture_descr: "Vines, permanent.",
	protectedSite: "protected site",
	protectedSite_descr: "Sites in nature conservation areas (raised bogs, in the National Park, …).",
	urbanPark: "urban park",
	urbanPark_descr: "Urban park (Winterthur, Lugano).",
	crop: "crop cultivation",
	grassland: "Grassland (intensive, less intensive, extensive)",
	forest: "Forest (deciduous-, mixed- und coniferous forest)",
	specialGrowing: "Special crops (vegetable-, fruit growing, viticulture)",
	other: "Other (protected site, urban park)",
	naboPlaces: "NABO permanent monitoring sites and use in 5th survey",
	titelParameter: "Description of heavy metal",
	Cd_descr: "Cadmium is particularly harmful to humans; the damage it causes affects, inter alia, the kidneys, bones and central nervous system. It reaches the soil via atmospheric deposition and as impurities in phosphorous fertilisers; depending on geological conditions, cadmium  levels can also be naturally elevated. Plants (some vegetables and wheat, in particular) absorb cadmium from the soil, and it enters the human food chain in this way.",
	Pb_descr: "The main way that lead enters the soil is through atmospheric deposition. Due to preventive measures, particularly the banning of lead in motor fuels, atmospheric lead pollution has declined considerably since the 1980s, and inputs into the soil are decreasing as a result. A high intake of lead is harmful to humans.",
	Cu_descr: "Copper reaches (reached) the soil as a component of plant protection products, particularly fungicides, and many vineyards and vegetable cultivation areas have elevated copper levels. Copper also reaches fields through the spreading of slurry and manure, as it is added to animal feed. Finally, copper levels can be naturally elevated due to geological conditions. Copper is essential for animals and humans in small quantities, however high levels are toxic.",
	Zn_descr: "Zinc reaches the soil via atmospheric deposition and through the spreading of slurry and manure; zinc levels can also be naturally elevated due to geological conditions. Zinc is an essential trace element for animals and humans. However, elevated levels in the soil can be harmful to plants and soil organisms.",
	Hg_descr: "Mercury is  a highly toxic heavy metal which accumulates in the food chain. Chronic exposure mainly results in damage to the kidneys and central nervous system. The intake of soil dust (or soil material by children) and inhalation of mercury vapours (mercury has high vapour pressure) pose a particular risk. Methylmercury is considered particularly toxic and is formed from mercury in the soil by microorganisms. Mercury reaches the environment through a large number of processes, in particular industry and combustion, however it is also contained in some plant protection products.",
	Ni_descr: "Levels of the elements nickel, chromium and cobalt are primarily determined by geology (geogenic content). Inputs arising from human activities are relevant at sites affected by direct environmental impacts (e.g. contaminated sites); such sites are not included in the NABO monitoring network.",
	Cr_descr: "Levels of the elements nickel, chromium and cobalt are primarily determined by geology (geogenic content). Inputs arising from human activities are relevant at sites affected by direct environmental impacts (e.g. contaminated sites); such sites are not included in the NABO monitoring network.",
	Co_descr: "Levels of the elements nickel, chromium and cobalt are primarily determined by geology (geogenic content). Inputs arising from human activities are relevant at sites affected by direct environmental impacts (e.g. contaminated sites); such sites are not included in the NABO monitoring network.",
	noHeavyMetal: "No heavy metal selected.",
	noLanduse: "No land use selected.",	
	unitValue: "mg/kg dry matter (DM)",
	unitValueShort: "mg/kg DM",
	unitValueLegend: "DM = dry matter",
	glossarUrl: "http://www.bafu.admin.ch/chemikalien/prtr/07159/index.html?lang=en",
	glossarUrlText: "Federal Office for the Environment (FOEN) glossary of pollutants",
	maxValue: "Maximum value",
	dateSampling: "Sampling date",
	parameterinfo: "Information about selected heavy metal",
	landuseinfo: "Information about land use",
	placeinfo: "Information about selected site",
	howto: "Temporal development",
	linkVis: "Data visualisation",
	linkNabo: "NABO website",
	nabo8504: "https://www.bafu.admin.ch/bafu/en/home/topics/soil/publications-studies/publications/nationale-bodenbeobachtung-nabo-1985-2004.html",
	nabo8509: "https://www.bafu.admin.ch/bafu/en/home/topics/soil/publications-studies/publications/bodenbeobachtung-nabo-1985-2009.html",
	pubtext8504: "Results of Swiss National Soil Monitoring (NABO) 1985−2004",
	pubtext8509: "Results of Swiss National Soil Monitoring (NABO) 1985−2009",
	noMeasurement: "Sampled, no measurement data",
	ubd0066: "http://www.ubst.bafu.admin.ch/opendata/UBD0066.ods",
	textubd0066: "Specification and data of the heavy metal load of the soil"
};